version: '3.5'

networks:
  webnet:
    driver: overlay
    attachable: true

services:
  web:
    image: "future_butcher_api:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:4000"
    env_file:
      - config/docker.env
    networks: 
      - webnet
